### ISSUE TITLE
Bot doesn't respond

### ISSUE THREAD

**Issue by sporkwitch** [ZiraDiscord/Zira#2]
Logs indicate it is connected to the db (localhost/Zira), user (ziraUser) is created with readWrite and dbAdmin perms for the Zira db, password is alphanumeric only (didn't seem to like symbols in the password).

No response from the z/help command (existing "official" zira bot does respond; I have my local instance sharing the bot account of my Mod Mail bot from Dragory).  Bot account has server admin perms.

No errors in logs since removing the trello lines in the config file.  No apparent errors, it's just non-responsive.

**Comment by sporkwitch** [comment]
Settings were unclear.  Thought prefix referred to DB settings for prefix on table names, and it overrides the default z/ prefix.  Removing prefix restored normal behaviour.

**Comment by Aardenfell** [comment]
@sporkwitch Could you share on how you setup your instance of Zira? My version isn't responding either

**Comment by sporkwitch** [comment]
Ensure you set up mongodb correctly (you'll need to create a db and a user) and that the bot is connecting to it.
